# Generated by Django 2.2.3 on 2019-12-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=30)),
                ('end', models.CharField(max_length=30)),
                ('tender_alloted_to', models.CharField(max_length=30)),
                ('complaints', models.IntegerField(default=0)),
            ],
        ),
    ]
