# Generated by Django 2.2.3 on 2019-12-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191220_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('0', 'Just Arrived'), ('1', 'In Progress'), ('2', 'Resolved')], default='0', max_length=1),
        ),
    ]
