# Generated by Django 2.2.3 on 2019-12-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_complaint_damage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='damage',
        ),
    ]
